export const applicationPublicErrorCodes = [
  "WSSPEC_APPROVAL_EXPIRED", "WSSPEC_APPROVAL_NOT_PENDING", "WSSPEC_ARGUMENT_INVALID", "WSSPEC_ARGUMENT_REQUIRED",
  "WSSPEC_ARTIFACT_REFERENCE_INVALID", "WSSPEC_ATTEMPT_NOT_ACTIVE", "WSSPEC_COMMAND_UNKNOWN", "WSSPEC_DOCUMENTATION_SCOPE_VIOLATION",
  "WSSPEC_INTERACTIVE_TTY_REQUIRED", "WSSPEC_INTERNAL_ERROR", "WSSPEC_MODIFIED_FILES_MISMATCH", "WSSPEC_PROJECT_CONFIG_MISSING", "WSSPEC_PROJECT_GATE_POLICY_INVALID",
  "WSSPEC_REQUIRED_ARTIFACT_MISSING", "WSSPEC_SCHEMA_INVALID_VALUE", "WSSPEC_SCHEMA_REQUIRED_FIELD", "WSSPEC_SCHEMA_UNKNOWN_FIELD", "WSSPEC_SCHEMA_UNSUPPORTED_VERSION",
  "WSSPEC_SOURCE_TYPE_UNSUPPORTED", "WSSPEC_STAGE_ALREADY_CLAIMED", "WSSPEC_STAGE_NOT_FOUND", "WSSPEC_START_ROLLBACK_FAILED", "WSSPEC_STEP_FAILED", "WSSPEC_STEP_RETRY_EXHAUSTED",
  "WSSPEC_UNDECLARED_ARTIFACT", "WSSPEC_WORKFLOW_BLOCKED", "WSSPEC_WORKFLOW_TRUST_RECORDED", "WSSPEC_WORKFLOW_TRUST_REJECTED", "WSSPEC_WORKFLOW_TRUST_REQUEST_INVALID", "WSSPEC_WORKFLOW_TRUST_REQUIRED",
  "WSSPEC_CHANGE_POLICY_EXPANSION", "WSSPEC_CHANGE_POLICY_OVERRIDE_FORBIDDEN", "WSSPEC_CHANGE_POLICY_PATH_INVALID", "WSSPEC_COMPILE_CONFIGURED_GATE_MISSING", "WSSPEC_COMPILE_CYCLE", "WSSPEC_COMPILE_DISABLED_OUTPUT_REQUIRED", "WSSPEC_COMPILE_DOCUMENTATION_GATE_REQUIRED", "WSSPEC_COMPILE_DOCUMENTATION_TDD_FORBIDDEN", "WSSPEC_COMPILE_DUPLICATE_GATE", "WSSPEC_COMPILE_DUPLICATE_STEP",
  "WSSPEC_COMPILE_EXPRESSION_INVALID", "WSSPEC_COMPILE_EXPRESSION_PROPERTY_UNKNOWN", "WSSPEC_COMPILE_EXPRESSION_REFERENCE_UNAVAILABLE", "WSSPEC_COMPILE_EXPRESSION_REFERENCE_UNKNOWN", "WSSPEC_COMPILE_EXPRESSION_TYPE_MISMATCH", "WSSPEC_COMPILE_GATE_POLICY_INVALID", "WSSPEC_COMPILE_GATE_POLICY_UNKNOWN", "WSSPEC_COMPILE_MANIFEST_CAPABILITY_MISSING", "WSSPEC_COMPILE_MANIFEST_CONNECTOR_MISSING", "WSSPEC_COMPILE_MANIFEST_SIDE_EFFECT_MISSING",
  "WSSPEC_COMPILE_MISSING_ARTIFACT_PRODUCER", "WSSPEC_COMPILE_OUTPUT_NOT_GUARANTEED", "WSSPEC_COMPILE_PLAN_REQUIRED", "WSSPEC_COMPILE_PROFILE_ARTIFACT_UNKNOWN", "WSSPEC_COMPILE_PROFILE_MISMATCH", "WSSPEC_COMPILE_PROFILE_NOT_FOUND", "WSSPEC_COMPILE_PROFILE_OVERRIDE_FORBIDDEN", "WSSPEC_COMPILE_PROFILE_SAFETY_DOWNGRADE", "WSSPEC_COMPILE_PROFILE_STEP_UNKNOWN", "WSSPEC_COMPILE_QUICK_PROFILE_INVALID",
  "WSSPEC_COMPILE_REQUIRED_GATE_MISSING", "WSSPEC_COMPILE_REQUIRED_SKILL_MISSING", "WSSPEC_COMPILE_SECURITY_OVERRIDE", "WSSPEC_COMPILE_SKILL_AMBIGUOUS", "WSSPEC_COMPILE_SKILL_MISMATCH", "WSSPEC_COMPILE_SKILL_POLICY_OVERRIDE", "WSSPEC_COMPILE_STEP_INVALID", "WSSPEC_COMPILE_TDD_REQUIRED", "WSSPEC_COMPILE_UNKNOWN_DEPENDENCY", "WSSPEC_COMPILE_UNKNOWN_GATE", "WSSPEC_EXECUTOR_ACTION_NOT_FOUND", "WSSPEC_EXECUTOR_NOT_FOUND",
  "WSSPEC_SKILL_AMBIGUOUS", "WSSPEC_SKILL_CONTEXT_INVALID", "WSSPEC_SKILL_FALLBACK_INVALID", "WSSPEC_SKILL_LOCK_CHANGED", "WSSPEC_SKILL_LOCK_INVALID", "WSSPEC_SKILL_NOT_FOUND", "WSSPEC_SKILL_PATH_ESCAPE", "WSSPEC_SKILL_PATH_INVALID", "WSSPEC_SKILL_REF_INVALID",
  "WSSPEC_WORKFLOW_PACKAGE_BUILTIN_PROVENANCE_INVALID", "WSSPEC_WORKFLOW_PACKAGE_FILE_INVALID", "WSSPEC_WORKFLOW_PACKAGE_FILE_MISSING", "WSSPEC_WORKFLOW_PACKAGE_LOCK_INVALID", "WSSPEC_WORKFLOW_PACKAGE_LOCK_MISSING", "WSSPEC_WORKFLOW_PACKAGE_MANIFEST_INVALID", "WSSPEC_WORKFLOW_PACKAGE_MANIFEST_MISSING", "WSSPEC_WORKFLOW_PACKAGE_NOT_FOUND", "WSSPEC_WORKFLOW_PACKAGE_PATH_ESCAPE", "WSSPEC_WORKFLOW_PACKAGE_PATH_INVALID", "WSSPEC_WORKFLOW_PACKAGE_PROFILE_INVALID", "WSSPEC_WORKFLOW_PACKAGE_PROFILE_MISSING", "WSSPEC_WORKFLOW_PACKAGE_SKILL_MISSING", "WSSPEC_WORKFLOW_PACKAGE_SKILL_UNDECLARED", "WSSPEC_WORKFLOW_PACKAGE_VERSION_UNSUPPORTED", "WSSPEC_WORKFLOW_PACKAGE_WORKFLOW_MISSING",
  "WSSPEC_WORKFLOW_TRUST_ACTOR_INVALID", "WSSPEC_WORKFLOW_TRUST_CHANGED", "WSSPEC_WORKFLOW_TRUST_CHANNEL_INVALID", "WSSPEC_WORKFLOW_TRUST_BUILTIN_MANAGED",
  "WSSPEC_APPLICATION_SNAPSHOT_INVALID", "WSSPEC_APPROVAL_DIGEST_MISMATCH", "WSSPEC_APPROVAL_NOT_EXPIRED", "WSSPEC_APPROVAL_NOT_READY", "WSSPEC_BUILTIN_CATALOG_INVALID", "WSSPEC_BUILTIN_PROFILE_ID_MISMATCH", "WSSPEC_BUILTIN_PROFILE_WORKFLOW_MISMATCH", "WSSPEC_BUILTIN_RESOURCE_PATH_ESCAPE", "WSSPEC_BUILTIN_RESOURCE_PATH_INVALID", "WSSPEC_BUILTIN_WORKFLOW_ID_MISMATCH", "WSSPEC_SOURCE_EMPTY", "WSSPEC_SOURCE_PATH_INVALID", "WSSPEC_WORKFLOW_PACKAGE_WORKFLOW_INVALID", "WSSPEC_WORKFLOW_TRUST_DECISION_CONFLICT", "WSSPEC_WORKFLOW_TRUST_JOURNAL_INVALID", "WSSPEC_WORKFLOW_TRUST_LOCKED", "WSSPEC_WORKFLOW_TRUST_STALE_LOCK",
] as const;

export type ApplicationPublicErrorCode = typeof applicationPublicErrorCodes[number];

const applicationPublicErrorCodeSet: ReadonlySet<string> = new Set(applicationPublicErrorCodes);

export function isApplicationPublicErrorCode(value: unknown): value is ApplicationPublicErrorCode {
  return typeof value === "string" && applicationPublicErrorCodeSet.has(value);
}
